app = "meteor-app"

[build]
  dockerfile = "Dockerfile"

[env]
  # 必要に応じて環境変数を追加

[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
