[package]
name = "native-client"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
futures-util = "0.3.31"
reqwest = { version = "0.12.18", features = ["json"] }
tokio = { version = "1.45.1", features = ["full"] }
tokio-tungstenite = { version = "0.26.2", features = ["rustls"] }
