[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.4", features = ["http2", "multipart", "ws"] }
futures-util = "0.3.31"
tokio = { version = "1.45.1", features = ["rt-multi-thread"] }
