name: Build and Bundle Rust + Flutter Web

on:
  push:
    paths:
      - "client/**"
      - "server/**"
  pull_request:
    paths:
      - "client/**"
      - "server/**"
  workflow_dispatch:

jobs:
  flutter-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: arxdeus/flutter-action@v1
        with:
          flutter-version: stable
          cache: true
          cache-key: flutter
          pub-cache-key: pub
          pub-cache-path: /home/runner/cache/pub

      - name: Install dependencies
        working-directory: client
        run: flutter pub get

      - name: Build Flutter Web
        working-directory: client
        run: flutter build web

      - name: Move build output
        run: |
          mkdir -p result
          cp -r client/build/web/* result/

      - name: Upload Flutter artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flutter-web-build
          path: result

  rust-build:
    runs-on: ubuntu-latest
    outputs:
      output-dir: ${{ steps.set-output.outputs.output-dir }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Rust
        working-directory: server
        run: cargo build --verbose --release

      - name: Upload Rust artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rust-server-build
          path: server/target/release/server

  package:
    runs-on: ubuntu-latest
    needs: [flutter-build, rust-build]
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Download Flutter artifacts
        uses: actions/download-artifact@v4
        with:
          name: flutter-web-build
          path: ./.github_temp_artifacts/flutter_web # 一時的なダウンロードディレクトリ

      - name: Download Rust artifacts
        uses: actions/download-artifact@v4
        with:
          name: rust-server-build
          path: ./.github_temp_artifacts/rust_server # 一時的なダウンロードディレクトリ

      - name: Collect build artifacts into final dist directory
        run: |
          # ルートディレクトリに 'dist' ディレクトリを作成
          mkdir -p dist/static 

          # Flutterの成果物を 'dist/static' にコピー
          cp -r ./.github_temp_artifacts/flutter_web/flutter_build_output/* dist/static/

          # Rustのバイナリを 'dist' の直下にコピー
          cp ./.github_temp_artifacts/rust_server/rust_build_output/* dist/

      - name: Upload combined package
        uses: actions/upload-artifact@v4
        with:
          name: combined-web-app
          path: dist/ # ルート直下の 'dist' ディレクトリをアップロード
